server:
  port: 8088

#spring:
#  datasource:
#    username: root
#    password: admin
#    url: jdbc:mysql://localhost:3306/mine?useUnicode=true&characterEncoding=utf8&useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver

spring:
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: admin
      url: jdbc:mysql://localhost:3306/mine?useUnicode=true&characterEncoding=utf-8&useSSL=false
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      validation-query: select 'x'
      validationQueryTimeout: 5
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.werlini.sbmp.model
